script/seed.js
server/db/models/index.js
server/db/models/suspects.js

Made seed file

---

client/components/levelOne.js
client/components/levelTwo.js
client/components/navbar.js
client/questions/level1Q.js
client/routes.js
client/store/index.js
client/store/questionStore.js
public/style.css

Added Redux store to Level 1

---

client/components/levelThree.js
public/style.css

Build table

---

client/components/levelOne.js
client/components/levelTwo.js
client/questions/level1Q.js
client/store/index.js
client/store/questionStore.js

feat: move between prompts and questions

---

client/components/countdownClock.js

fix: fixed clock export

---

client/components/home.js
public/style.css

added intro msg style

---

client/components/countdownClock.js
client/components/home.js
public/style.css

Integration branch

---

client/components/levelOne.js
public/style.css
server/api/sqlMiddleware.js
server/api/suspects.js
server/index.js

feature: sql parse string

---

client/components/levelOne.js

fix: fixed semicolon check bug

---

client/components/levelOne.js
server/api/sqlMiddleware.js
server/api/suspects.js

feature: disable middleware

---

client/components/CodeEditor.js
client/components/FakeTerminal.js
client/components/levelOne.js
client/components/navbar.js
client/questions/level1Q.js
client/store/questionStore.js

Update: started modularizing Level 1 and added Store to navbar

---

client/components/navbar.js
client/components/table.js
public/index.html
public/style.css

Jackie animation

---

.gitignore
client/components/FakeTerminal.js
client/components/levelOne.js
client/questions/level1Q.js
package-lock.json
package.json
public/style.css
webpack.config.js

Update: cleaned up story flow

---

client/components/FakeTerminal.js
client/components/levelOne.js
client/questions/level1Q.js
public/style.css
server/api/sqlMiddleware.js
server/api/suspects.js
webpack.config.js

features: hint pop-up; incorrect query handler

---

client/components/FakeTerminal.js
client/components/levelOne.js
client/questions/level1Q.js
public/codeMirror.css

Update: added more hint functionality

---

client/components/FakeTerminal.js
client/components/levelOne.js
client/components/levelTwo.js
client/questions/level1Q.js
public/style.css

chore: first couple of clues

---

.travis.yml

chore: add travis info

---

.travis.yml

chore: api key fix

---

.travis.yml

fix: new api key

---

client/components/CodeEditor.js
client/components/FakeTerminal.js
client/components/levelTwo.js
client/components/navbar.js
client/questions/level1Q.js
client/questions/level2Q.js
client/store/questionStore.js

Feature: level 2 functionality

---

client/components/FakeTerminal.js
client/questions/level1Q.js

Update: hints now type on terminal

---

.travis.yml

fix: another travis fix

---

client/components/CodeEditor.js
client/components/levelOne.js
client/components/levelTwo.js
client/questions/level2Q.js
script/data.js
server/api/alibis.js
server/api/index.js
server/api/sqlMiddleware.js
server/db/models/alibis.js

feature: level 2 game flow complete

---

client/components/CodeEditor.js
client/components/levelOne.js
server/api/alibis.js
server/api/sqlMiddleware.js

fix: level 1 and 2 bugs

---

server/api/alibis.js
server/api/sqlMiddleware.js

fix: fixed level 1 and 2 bugs

---

client/components/levelThree.js
client/questions/level2Q.js
client/questions/level3Q.js

Added Level 2 hints

---

client/components/levelOne.js
client/components/levelTwo.js

added transitions

---

.travis.yml

fix: fixed travis file

---

client/components/table.js

fix: fixing postgres

---

README.md
client/components/table.js

fix: changed heroku tables

---

client/components/levelOne.js
client/components/levelThree.js
client/components/levelTwo.js
client/questions/level1Q.js
client/questions/level2Q.js
client/questions/level3Q.js
server/api/sqlMiddleware.js

Update: fixing hints on all levels
